// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJvAlmdX0_sR2YJWjRpn1vvZ33CkGtDZU',
    appId: '1:693280855291:web:704e6a8df8119f05460c5e',
    messagingSenderId: '693280855291',
    projectId: 'bizzflow-f99c0',
    authDomain: 'bizzflow-f99c0.firebaseapp.com',
    storageBucket: 'bizzflow-f99c0.firebasestorage.app',
    measurementId: 'G-947XQD0FRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbqujds0HqwdFku_ts3jFQdqmTo7EdzPc',
    appId: '1:693280855291:android:a7161806e250b0ba460c5e',
    messagingSenderId: '693280855291',
    projectId: 'bizzflow-f99c0',
    storageBucket: 'bizzflow-f99c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj91kvf6mfxfIcnsi-c8IbYGuMponTCI8',
    appId: '1:693280855291:ios:9c1e8f88564dc46a460c5e',
    messagingSenderId: '693280855291',
    projectId: 'bizzflow-f99c0',
    storageBucket: 'bizzflow-f99c0.firebasestorage.app',
    iosBundleId: 'com.example.bizzflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj91kvf6mfxfIcnsi-c8IbYGuMponTCI8',
    appId: '1:693280855291:ios:9c1e8f88564dc46a460c5e',
    messagingSenderId: '693280855291',
    projectId: 'bizzflow-f99c0',
    storageBucket: 'bizzflow-f99c0.firebasestorage.app',
    iosBundleId: 'com.example.bizzflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJvAlmdX0_sR2YJWjRpn1vvZ33CkGtDZU',
    appId: '1:693280855291:web:5e2765d8f1c0f0e6460c5e',
    messagingSenderId: '693280855291',
    projectId: 'bizzflow-f99c0',
    authDomain: 'bizzflow-f99c0.firebaseapp.com',
    storageBucket: 'bizzflow-f99c0.firebasestorage.app',
    measurementId: 'G-XKMXDXHNLD',
  );
}
